name: projetfe
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'
null_safety: true


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  cupertino_icons: ^1.0.2
  scroll_snap_list: ^0.9.1
  table_calendar: ^3.1.0
  percent_indicator: ^4.2.3
  image_picker: ^0.8.4+4
  path_provider: ^2.0.5
  http_parser: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/logo.jpg
    - assets/images/22.png
    - assets/images/coachP.jpg
    - assets/images/1.jpg
    - assets/images/3.jpg
    - assets/images/4.jpg
    - assets/images/5.jpg
    - assets/images/eau.jpg
    - assets/images/ech.jpg
    - assets/images/entr.jpg
    - assets/images/corps.jpg
    - assets/images/pyramide.jpg
    - assets/images/conseil.jpg
    - assets/images/alimentation.jpg
    - assets/images/battement.jpg
    - assets/images/température.jpg
    - assets/images/fp1.jpg
    - assets/images/fp2.jpeg
    - assets/images/gym_image.jpg
    - assets/images/user_avatar.jpg
    - assets/images/suivi.jpg
    - assets/images/tarif.png
    - assets/images/gymnastique.jpg
    - assets/images/karate.jpg
    - assets/images/kickboxing.jpg
    - assets/images/musculation.jpg
    - assets/images/zumba.jpg
    - assets/images/btmc.png
    - assets/images/temp.jpg

















  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
